// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jexczwnpirrgvywdmjeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpleGN6d25waXJyZ3Z5d2RtamVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzgyODcsImV4cCI6MjA2NTg1NDI4N30.2v10eSRNduYrMt76D_Q4Z9596pi6KAIXUTLrl4sKSpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);